name: flutter_testrail
description: This package is a lightweight wrapper around the TestRail API that enables automated test reporting in Dart and Flutter applications.
homepage: https://github.com/amitsingh6391/flutter_testrail
issue_tracker: https://github.com/amitsingh6391/flutter_testrail/issues
repository: https://github.com/amitsingh6391/flutter_testrail
version: 1.0.3


environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  lints: ^2.1.1

flutter: